### PR TITLE
Guessing game -> html css javascript

### PR DESCRIPTION
**Pull request by gulatikeshav**
please review my code and merge it.
thank you!!

### CODE REVIEW

**Comment by solygambas** [comment]
Thank you, feel free to fork the repo and add your own projects :)

**Comment by gulatikeshav** [comment]
@solygambas  add your own projects :), what does it mean ?

**Comment by gulatikeshav** [comment]
I upload files from my laptop only , not from online resources 

so, can you merge my pr

**Comment by solygambas** [comment]
https://docs.github.com/articles/fork-a-repo You fork this repo on your own profile, then you can add your projects.

**Pull request closed without merging**
